name: Build Play Store Android App

on:
  workflow_dispatch:
    inputs:
      gist_id:
        description: 'Gist ID'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install requests
      - run: python injector.py ${{ github.event.inputs.gist_id }}
      - uses: actions/setup-java@v4
        with: { java-version: '21', distribution: 'temurin', cache: 'gradle' }
      - env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > app/release-key.jks
      - env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease bundleRelease
          
      - name: Upload APK to Temp Host (Bypass GitHub Limits)
        run: |
          APK_LINK=$(curl -s -H "Max-Days: 1" --upload-file app/build/outputs/apk/release/app-release.apk https://transfer.sh/app-release.apk)
          echo "### 🚀 Build Complete!" >> $GITHUB_STEP_SUMMARY
          echo "🔗 **Download APK:** [Click Here to Download]($APK_LINK)" >> $GITHUB_STEP_SUMMARY
          
      - name: Upload AAB to Temp Host
        run: |
          AAB_LINK=$(curl -s -H "Max-Days: 1" --upload-file app/build/outputs/bundle/release/app-release.aab https://transfer.sh/app-release.aab)
          echo "🔗 **Download AAB (Play Store):** [Click Here to Download]($AAB_LINK)" >> $GITHUB_STEP_SUMMARY